#------------------------------
#Developer: Drew Lamb
#Created on: 4/1/16
#Last Updated: 4/1/16
#Description: Simple makefile for question 12. make all: creaates question12.exe
#	make clean: removes .o and .exe files
#-------------------------------

all: question12.cpp
	g++ question12.cpp -o question12.exe

clean:
	rm *.exe*
