#------------------------------
#Developer: Drew Lamb
#Created on: 4/1/16
#Last Updated: 4/1/16
#Description: Simple makefile for question 13. make all: creaates question13.exe
#	make clean: removes .o and .exe files
#-------------------------------

all: question13.cpp
	g++ question13.cpp -o question13.exe

clean:
	rm *.exe*
